### PR TITLE
Fix announcement bug

### LINKED ISSUE #40: Anouncement Bug
announcement_bug_cropped

Gabriele announced kontra and I had the kontra dropdown open, announcing only milliseconds later.
To be honest I don't remember if we got an extra point (don't think so), but announcing twice shouldn't be possible by game logic.

### PR DESCRIPTION
**Pull request by davidkaufmann**
Removes already announced Announcements from your teammate from the `possibleannouncement()` function.
Hence it's not possible to announce the same as your teammate.

fixes #40

### CODE REVIEW

File: frontend/src/models/player.ts [hunk 1]
```diff
@@ -172,10 +172,28 @@ export class Player {
...
+  }
+
+  getTeammateAnnouncements(): Set<Announcement> {
+    return (
+      this.game?.players.find(
+        player => this.id !== player.id && this.isRe() === player.isRe()
+      )?.announcements || new Set<Announcement>()
+    );
+  }
+
```
Comment (hamvocke) [inline frontend/src/models/player.ts:196]: These methods don't seem to be related to a single player but a party of players instead. I think it might be better putting them into [party.ts](https://github.com/hamvocke/doppelkopf/blob/master/frontend/src/models/party.ts) instead.

File: frontend/src/models/player.ts [hunk 2]
```diff
@@ -172,10 +172,28 @@ export class Player {
     notifier.info("player-announced-" + announcement, { name: this.name });
   }
 
-  hasAnnounced(...announcements: Announcement[]) {
+  hasAnnounced(...announcements: Announcement[]): boolean {
```
Comment (hamvocke) [inline frontend/src/models/player.ts:175]: just by looking at the method signature, I find it impossible to distinguish between `hasAnnounced(announcements): boolean` and `wasAnnounced(announcements): boolean`. Maybe moving it to `party.ts` helps, but maybe this needs some clearer naming on top.

**Review by hamvocke — CHANGES_REQUESTED** [review]
Looks good so far, thanks for the fix. Left two comments about code clarity, would be cool if you could fix that before we're getting the change in :)

File: frontend/src/models/player.ts (hunk 1 above)
Comment (davidkaufmann) [reply frontend/src/models/player.ts]: Oh wow. I never actually noticed party.ts 😅 
I'm using it now obviously and probably will be adding some functionality regarding silent weddings 👍🏻

`hasTeammateAnnounced()` has been removed since it's only been used for testing.
`getTeammateAnnouncements()` is actually already implemented by party.ts, i instead added a private function which passes it's result, dependign on the team you're playing in. Therefore `getParty()` has been introduced.

File: frontend/src/models/player.ts (hunk 2 above)
Comment (davidkaufmann) [reply frontend/src/models/player.ts]: You're right.
`hasAnnounced()` has been removed, since it wasn't used anyway - don't know why I didn't notice 😭
I am using `hasPartyAnnounced()` instead of `wasAnnounced()` now, so it's only `hasPartyAnnounced(announcements): boolean` left over which should be clear enough 👍🏻
